import { Calistoga, Outfit } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Breadcrumb } from "@/components/breadcrumb";
import Search from "@/components/Search";
import { GitCommitVertical } from "lucide-react";

const outfit = Outfit({ subsets: ["latin"], variable: "--fonts-san" });
const calistoga = Calistoga({
  subsets: ["latin"],
  variable: "--fonts-serif",
  weight: "400",
});

export const metadata = {
  title: "Homework 5",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${calistoga.variable} light`}>
        <div className="flex bg-gray-100">
          {children}
        </div>
      </body>
    </html>
  );
}
